# Settings that the LAMMPS build will import when this package library is used

user-atc_SYSINC =
user-atc_SYSLIB = -lmkl_scalapack_ilp64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_ilp64 -lpthread -lm
user-atc_SYSPATH = -L/share/apps/intel/2011/composer_xe_2011_sp1.10.319/mkl/lib/intel64
